select nombre from producto;
select nombre, precio from producto;
select * from producto;
select nombre, truncate(precio * 1.20,2) from producto;
select nombre as 'nom de producto', precio as euros, truncate(precio * 1.20,2) as dolars from producto;
select UPPER(nombre), precio from producto;
select LOWER(nombre), precio from producto;
select nombre, upper(substring(nombre,1,2)) from fabricante;
select nombre, round(precio) from producto;
select nombre, truncate(precio,0) from producto;
select codigo_fabricante from producto;
select distinct codigo_fabricante from producto;
select nombre from fabricante order by nombre asc;
select nombre from fabricante order by nombre desc;
select nombre from producto order by nombre asc, precio desc;
select * from fabricante limit 5;
select * from fabricante limit 3, 2;
select nombre, precio from producto order by precio asc limit 1;
select nombre, precio from producto order by precio desc limit 1;
select nombre from producto where codigo_fabricante = 2;
select producto.nombre, producto.precio, fabricante.nombre as fabricante from producto left join fabricante on fabricante.codigo=producto.codigo_fabricante;
select producto.nombre, producto.precio, fabricante.nombre as fabricante from producto left join fabricante on fabricante.codigo=producto.codigo_fabricante order by fabricante.nombre;
select producto.codigo, producto.nombre, producto.codigo_fabricante, fabricante.nombre as fabricante from producto left join fabricante on fabricante.codigo=producto.codigo_fabricante;
select producto.nombre, producto.precio, fabricante.nombre as fabricante from producto left join fabricante on producto.codigo_fabricante=fabricante.codigo order by precio limit 1;
select producto.nombre, producto.precio, fabricante.nombre as fabricante from producto left join fabricante on producto.codigo_fabricante=fabricante.codigo order by precio desc limit 1;
select * from producto where codigo_fabricante=2;
select * from producto where codigo_fabricante=6 and precio>200;
select * from producto where codigo_fabricante=1 or codigo_fabricante=3 or codigo_fabricante=5;
select * from producto where codigo_fabricante in (1, 3, 5);
select producto.nombre, producto.precio from producto join fabricante on producto.codigo_fabricante=fabricante.codigo and fabricante.nombre like '%e';
select producto.nombre, producto.precio from producto join fabricante on producto.codigo_fabricante=fabricante.codigo and fabricante.nombre like '%w%';
select producto.nombre, producto.precio, fabricante.nombre from producto join fabricante on producto.codigo_fabricante=fabricante.codigo and producto.precio>=180 order by producto.precio desc, producto.nombre;
select distinct fabricante.codigo, fabricante.nombre from fabricante join producto on fabricante.codigo=producto.codigo_fabricante;
select * from fabricante left join producto on fabricante.codigo=producto.codigo_fabricante;
select * from fabricante where (fabricante.codigo in (select distinct producto.codigo_fabricante from producto) is not true);
select * from producto where producto.codigo_fabricante=2;
select * from producto where  producto.precio='559';
select producto.nombre from producto join fabricante on fabricante.codigo=producto.codigo_fabricante and fabricante.nombre='Lenovo' order by producto.precio desc limit 1;
select producto.nombre from producto join fabricante on fabricante.codigo=producto.codigo_fabricante and fabricante.nombre='Hewlett-Packard' order by producto.precio limit 1;
select producto.nombre from producto where producto.precio >= (select producto.precio from producto join fabricante on fabricante.codigo=producto.codigo_fabricante and fabricante.nombre='Lenovo' order by producto.precio desc limit 1);
select producto.nombre from producto join fabricante on fabricante.codigo=producto.codigo_fabricante and fabricante.nombre='Asus' and producto.precio>(select distinct avg(precio) from producto join fabricante on fabricante.codigo=producto.codigo_fabricante and fabricante.nombre='Asus');

